name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: '63.34.140.33'
        username: 'ubuntu'
        key: ${{ secrets.DEPLOYER_KEY }}
        port: 22
        script: ./update_acss.sh
